# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import argparse
import functools
from pathlib import Path
from typing import Optional

import numpy as np
from gluonts.dataset.arrow import ArrowWriter
from joblib import Parallel, delayed
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import (
    RBF,
    ConstantKernel,
    DotProduct,
    ExpSineSquared,
    Kernel,
    RationalQuadratic,
    WhiteKernel,
)
from tqdm.auto import tqdm

LENGTH = 1024
KERNEL_BANK = [
    ExpSineSquared(periodicity=24 / LENGTH),  # H
    ExpSineSquared(periodicity=48 / LENGTH),  # 0.5H
    ExpSineSquared(periodicity=96 / LENGTH),  # 0.25H
    ExpSineSquared(periodicity=24 * 7 / LENGTH),  # H
    ExpSineSquared(periodicity=48 * 7 / LENGTH),  # 0.5H
    ExpSineSquared(periodicity=96 * 7 / LENGTH),  # 0.25H
    ExpSineSquared(periodicity=7 / LENGTH),  # D
    ExpSineSquared(periodicity=14 / LENGTH),  # 0.5D
    ExpSineSquared(periodicity=30 / LENGTH),  # D
    ExpSineSquared(periodicity=60 / LENGTH),  # 0.5D
    ExpSineSquared(periodicity=365 / LENGTH),  # D
    ExpSineSquared(periodicity=365 * 2 / LENGTH),  # 0.5D
    ExpSineSquared(periodicity=4 / LENGTH),  # W
    ExpSineSquared(periodicity=26 / LENGTH),  # W
    ExpSineSquared(periodicity=52 / LENGTH),  # W
    ExpSineSquared(periodicity=4 / LENGTH),  # M
    ExpSineSquared(periodicity=6 / LENGTH),  # M
    ExpSineSquared(periodicity=12 / LENGTH),  # M
    ExpSineSquared(periodicity=4 / LENGTH),  # Q
    ExpSineSquared(periodicity=4 * 10 / LENGTH),  # Q
    ExpSineSquared(periodicity=10 / LENGTH),  # Y
    DotProduct(sigma_0=0.0),
    DotProduct(sigma_0=1.0),
    DotProduct(sigma_0=10.0),
    RBF(length_scale=0.1),
    RBF(length_scale=1.0),
    RBF(length_scale=10.0),
    RationalQuadratic(alpha=0.1),
    RationalQuadratic(alpha=1.0),
    RationalQuadratic(alpha=10.0),
    WhiteKernel(noise_level=0.1),
    WhiteKernel(noise_level=1.0),
    ConstantKernel(),
]


def random_binary_map(a: Kernel, b: Kernel):
    """
    Applies a random binary operator (+ or *) with equal probability
    on kernels ``a`` and ``b``.

    Parameters
    ----------
    a
        A GP kernel.
    b
        A GP kernel.

    Returns
    -------
        The composite kernel `a + b` or `a * b`.
    """
    binary_maps = [lambda x, y: x + y, lambda x, y: x * y]
    return np.random.choice(binary_maps)(a, b)


def sample_from_gp_prior(
    kernel: Kernel, X: np.ndarray, random_seed: Optional[int] = None
):
    """
    Draw a sample from a GP prior.

    Parameters
    ----------
    kernel
        The GP covaraince kernel.
    X
        The input "time" points.
    random_seed, optional
        The random seed for sampling, by default None.

    Returns
    -------
        A time series sampled from the GP prior.
    """
    if X.ndim == 1:
        X = X[:, None]

    assert X.ndim == 2
    gpr = GaussianProcessRegressor(kernel=kernel)
    ts = gpr.sample_y(X, n_samples=1, random_state=random_seed)

    return ts


def sample_from_gp_prior_efficient(
    kernel: Kernel,
    X: np.ndarray,
    random_seed: Optional[int] = None,
    method: str = "eigh",
):
    """
    Draw a sample from a GP prior. An efficient version that allows specification
    of the sampling method. The default sampling method used in GaussianProcessRegressor
    is based on SVD which is significantly slower that alternatives such as `eigh` and
    `cholesky`.

    Parameters
    ----------
    kernel
        The GP covaraince kernel.
    X
        The input "time" points.
    random_seed, optional
        The random seed for sampling, by default None.
    method, optional
        The sampling method for multivariate_normal, by default `eigh`.

    Returns
    -------
        A time series sampled from the GP prior.
    """
    if X.ndim == 1:
        X = X[:, None]

    assert X.ndim == 2

    cov = kernel(X)
    ts = np.random.default_rng(seed=random_seed).multivariate_normal(
        mean=np.zeros(X.shape[0]), cov=cov, method=method
    )

    return ts


def generate_time_series(max_kernels: int = 5):
    """Generate a synthetic time series from KernelSynth.

    Parameters
    ----------
    max_kernels, optional
        The maximum number of base kernels to use for each time series, by default 5

    Returns
    -------
        A time series generated by KernelSynth.
    """
    while True:
        X = np.linspace(0, 1, LENGTH)

        # Randomly select upto max_kernels kernels from the KERNEL_BANK
        selected_kernels = np.random.choice(
            KERNEL_BANK, np.random.randint(1, max_kernels + 1), replace=True
        )

        # Combine the sampled kernels using random binary operators
        kernel = functools.reduce(random_binary_map, selected_kernels)

        # Sample a time series from the GP prior
        try:
            ts = sample_from_gp_prior(kernel=kernel, X=X)
        except np.linalg.LinAlgError as err:
            print("Error caught:", err)
            continue

        # The timestamp is arbitrary
        return {"start": np.datetime64("2000-01-01 00:00", "s"), "target": ts.squeeze()}


def sample_random_correlation_matrix(num_variables: int) -> np.ndarray:
    """Sample a random positive definite correlation matrix.

    The matrix is generated from a random covariance matrix and then shrunk
    towards identity to avoid near-singular cases.
    """
    if num_variables < 1:
        raise ValueError(f"Expected num_variables >= 1, but found {num_variables}.")

    if num_variables == 1:
        return np.eye(1, dtype=np.float64)

    gaussian_matrix = np.random.normal(size=(num_variables, num_variables))
    covariance = gaussian_matrix @ gaussian_matrix.T
    std = np.sqrt(np.diag(covariance))
    correlation = covariance / np.outer(std, std)

    shrinkage = np.random.uniform(0.1, 0.4)
    correlation = (1.0 - shrinkage) * correlation + shrinkage * np.eye(num_variables)
    correlation = (correlation + correlation.T) / 2
    correlation += 1e-6 * np.eye(num_variables)

    return correlation


def apply_cotemporaneous_multivariatizer(
    base_targets: np.ndarray,
    correlation_matrix: Optional[np.ndarray] = None,
) -> np.ndarray:
    """Inject instantaneous cross-variable correlation into univariate series.

    Parameters
    ----------
    base_targets
        Array of shape (num_variables, time_length) containing independent base
        univariate time series.
    correlation_matrix, optional
        Positive definite target correlation matrix of shape
        (num_variables, num_variables). When not provided, a random correlation
        matrix is sampled.

    Returns
    -------
    np.ndarray
        Correlated multivariate time series with shape
        (num_variables, time_length).
    """
    if base_targets.ndim != 2:
        raise ValueError(
            f"Expected base_targets to be 2D with shape (num_variables, time_length), got {base_targets.shape}."
        )

    num_variables, _ = base_targets.shape
    if correlation_matrix is None:
        correlation_matrix = sample_random_correlation_matrix(num_variables)
    else:
        correlation_matrix = np.asarray(correlation_matrix, dtype=np.float64)
        if correlation_matrix.shape != (num_variables, num_variables):
            raise ValueError(
                "Expected correlation_matrix to have shape "
                f"({num_variables}, {num_variables}), got {correlation_matrix.shape}."
            )
        correlation_matrix = (correlation_matrix + correlation_matrix.T) / 2
        np.linalg.cholesky(correlation_matrix)

    means = base_targets.mean(axis=1, keepdims=True)
    stds = base_targets.std(axis=1, keepdims=True)
    stds = np.where(stds < 1e-6, 1.0, stds)

    standardized_targets = (base_targets - means) / stds
    mixing_matrix = np.linalg.cholesky(correlation_matrix)
    correlated_targets = mixing_matrix @ standardized_targets

    # Restore each variable's marginal location and scale after correlation injection.
    return correlated_targets * stds + means


def generate_cotemporaneous_multivariate_time_series(
    num_variables: int,
    max_kernels: int = 5,
    correlation_matrix: Optional[np.ndarray] = None,
):
    """Generate one multivariate time series via a cotemporaneous multivariatizer.

    The base univariate series are first generated independently with
    ``generate_time_series`` and then mixed with a Cholesky factor so that the
    variables become correlated at the same time index.
    """
    if num_variables < 1:
        raise ValueError(f"Expected num_variables >= 1, but found {num_variables}.")

    base_series = [generate_time_series(max_kernels=max_kernels) for _ in range(num_variables)]
    base_targets = np.stack([series["target"] for series in base_series], axis=0)
    multivariate_target = apply_cotemporaneous_multivariatizer(
        base_targets=base_targets,
        correlation_matrix=correlation_matrix,
    )

    return {
        "start": base_series[0]["start"],
        "target": multivariate_target,
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-N", "--num-series", type=int, default=1000_000)
    parser.add_argument("-J", "--max-kernels", type=int, default=5)
    parser.add_argument(
        "-V",
        "--num-variables",
        type=int,
        default=1,
        help="Number of variables per generated series. Values > 1 use the cotemporaneous multivariatizer.",
    )
    parser.add_argument(
        "-O",
        "--output-path",
        type=Path,
        default=None,
        help="Optional output path. Defaults depend on whether the output is univariate or multivariate.",
    )
    args = parser.parse_args()

    if args.output_path is None:
        default_filename = (
            "kernelsynth-data.arrow"
            if args.num_variables == 1
            else "kernelsynth-cotemporaneous-multivariate-data.arrow"
        )
        path = Path(__file__).parent / default_filename
    else:
        path = args.output_path

    generated_dataset = Parallel(n_jobs=-1)(
        (
            delayed(generate_time_series)(max_kernels=args.max_kernels)
            if args.num_variables == 1
            else delayed(generate_cotemporaneous_multivariate_time_series)(
                num_variables=args.num_variables,
                max_kernels=args.max_kernels,
            )
        )
        for _ in tqdm(range(args.num_series))
    )

    ArrowWriter(compression="lz4").write_to_file(
        generated_dataset,
        path=path,
    )
